local ls = require("luasnip")

local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s("class", {
    t("class "),
    i(1, "ClassName"),
    t({ " {", "public:", " " }),
    i(2),
    t({ "", "};" }),
    i(0),
  }),
  s("sgetter", { -- Set/Get Function
    t("void set_"),
    i(1, "type"),
    t("(const "),
    i(2, "Type"),
    t(" &a_"),
    rep(1),
    t(") { m_"),
    rep(1),
    t(" = a_"),
    rep(1),
    t({ "; };", "" }),
    rep(2),
    t(" get_"),
    rep(1),
    t("() const { return m_"),
    rep(1),
    t("; };"),
    i(0),  
  }),
  s("BindMethod", { -- Bind Set/Get and Add Property
    t('ClassDB::bind_method(D_METHOD("set_'),
    i(1, "type"),
    t('", "'),
    i(2, "type_name"),
    t('"), &'),
    i(3, "class_name"),
    t("::set_"),
    rep(1),
    t({ ");", 'ClassDB::bind_method(D_METHOD("get_'}),
    rep(1),
    t('"), &'),
    rep(3),
    t("::get_"),
    rep(1),
    t({ ');', 'ADD_PROPERTY(PropertyInfo(Variant::' }),
    i(4, "TYPE"),
    t(', "m_'),
    rep(1),
    t('"), "set_'),
    rep(1),
    t('", "get_'),
    rep(1),
    t('");'),
    i(0),
  }),
}
